potatoengine/potato

source/library/ecs/private/world.cpp
source/library/ecs/public/potato/ecs/query.h
source/library/ecs/public/potato/ecs/world.h

The reverse mapping of indices was totally botched.
Instead now we simplify by storing both the sorted components for
matching and the original-order components for lookup/unpacking.

Fix bug in ECS queries

---

source/library/ecs/private/archetype.h
source/library/ecs/private/world.cpp
source/library/ecs/public/potato/ecs/query.h
source/library/ecs/public/potato/ecs/world.h
source/library/ecs/tests/test_world.cpp

Component array index was used for layout array, even though the latter is sorted and the indices no longer match.
Split the code into a separate function to make that kind of error harder.

ECS fix for layout calculations

---

.github/workflows/main.yml

Will let use remove the (unplublishable) potatoengine ghactiosn repo,
and ensure I only need to support one set of actions going forward.

Use the separated ghactions that are published

---

source/librecon/private/converter_app.cpp
source/libruntime/private/uuid.cpp
source/libruntime/private/uuid.darwin.cpp
source/libruntime/private/uuid.linux.cpp
source/libruntime/private/uuid.windows.cpp
source/libruntime/public/potato/runtime/uuid.h
source/libruntime/tests/test_uuid.cpp
source/spud/public/potato/spud/CMakeLists.txt
source/spud/public/potato/spud/ascii.h

Same functionality. New fancy style.
- Got rid of `using namespace up` since that will cause pain with blob builds.
- Normalized style to rest of code.
- Renamed to `UUID` since it's not in spud (stl replacement) anymore.
- Removed redundant `zero()` static function.
- Made `toString()` a non-static member function.
- Added support to parse `{ABCD-...-XYWZ}` style guids.
- Split platform code into separate per-platform files.
- Made it `constexpr`-friendly; required some rejiggering of storage and removal of `memcpy` in common cases.

UUID style updates

---

source/libecs/private/entity_id.h
source/libecs/private/world.cpp
source/libecs/public/potato/ecs/world.h
source/libecs/tests/test_world.cpp

Prior simplication caused EntityIds to be corrupted.
Added a test to ensure this is caught if it breaks again.

Fix component addition/removal

---

CMakeLists.txt

Latest VS preview is keeping backslashes in some paths that it didn't before.
This results in malformed JSON for generated config files.

Fix Windows paths exported to JSON

---

source/bin_recon/private/recon_app.cpp
source/bin_recon/private/recon_app.h
source/librecon/private/recon_client.cpp
source/librecon/schema/recon_messages.sap

- Replaces assuming the manifest is dirty after each log message
- Flushes manifest stream before sending message
Should fix the race condition that results in the manifest sometimes being corrupted

Explicit message for after a manifest is written

---

resources/materials/basic.mat
resources/materials/full.mat
source/bin_recon/private/recon_app.cpp
source/bin_shell/private/editors/asset_browser.cpp
source/bin_shell/private/editors/asset_browser.h
source/bin_shell/private/editors/scene_editor.cpp
source/librender/private/material.cpp
source/librender/schemas/material.fbs
source/libruntime/private/asset_loader.cpp
source/libruntime/private/resource_manifest.cpp
source/libruntime/private/uuid.cpp
source/libruntime/public/potato/runtime/asset_loader.h
source/libruntime/public/potato/runtime/resource_manifest.h
source/libruntime/public/potato/runtime/uuid.h
source/libruntime/tests/test_resource_manifest.cpp
source/libtools/private/asset_library.cpp
source/libtools/private/importer_context.cpp
source/libtools/private/importers/material_importer.cpp
source/libtools/public/potato/tools/asset_library.h
source/libtools/public/potato/tools/importer.h
source/libtools/public/potato/tools/importer_context.h
source/libtools/public/potato/tools/importers/copy_importer.h
source/libtools/public/potato/tools/importers/hlsl_importer.h
source/libtools/public/potato/tools/importers/ignore_importer.h
source/libtools/public/potato/tools/importers/json_importer.h
source/libtools/public/potato/tools/importers/material_importer.h
source/libtools/public/potato/tools/importers/model_importer.h

Closes #228 
- Replaces the use of the hashed file path as the primary source asset id
- Replaces use of hashed file path + logical name with hashed uuid + logical name for logical id
Todo:

Plumb UUID as primary source asset ID

---

.github/workflows/main.yml
CMakeSettings.json
source/libformat/public/potato/format/_detail/format_impl.h

Enable more warnings in MSVC builds to help catch the kinds of things that clang-tidy dislikes.
/w34295 -- https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4295?view=msvc-160
/w34189 -- https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4189?view=msvc-160

Enable more warnings in MSVC

---

source/bin_shell/private/shell_app.cpp

Was hard-coded to only opening the scene editor

Open correct editor for asset

---

source/bin_shell/private/shell_app.cpp

Make it less ginarmous or awkward on large or ultra-wide monitors

Tweak default shell window size

---

CMakeLists.txt
depends.cmake
external/dx12memalloc.cmake
potato/librender/CMakeLists.txt
potato/librender/source/d3d12_backend/CMakeLists.txt
potato/librender/source/d3d12_backend/d3d12_buffer.cpp
potato/librender/source/d3d12_backend/d3d12_buffer.h
potato/librender/source/d3d12_backend/d3d12_command_list.cpp
potato/librender/source/d3d12_backend/d3d12_command_list.h
potato/librender/source/d3d12_backend/d3d12_desc_heap.cpp
potato/librender/source/d3d12_backend/d3d12_desc_heap.h
potato/librender/source/d3d12_backend/d3d12_device.cpp
potato/librender/source/d3d12_backend/d3d12_device.h
potato/librender/source/d3d12_backend/d3d12_factory.cpp
potato/librender/source/d3d12_backend/d3d12_factory.h
potato/librender/source/d3d12_backend/d3d12_pipeline_state.cpp
potato/librender/source/d3d12_backend/d3d12_pipeline_state.h
potato/librender/source/d3d12_backend/d3d12_platform.cpp
potato/librender/source/d3d12_backend/d3d12_platform.h
potato/librender/source/d3d12_backend/d3d12_resource_view.cpp
potato/librender/source/d3d12_backend/d3d12_resource_view.h
potato/librender/source/d3d12_backend/d3d12_root_signature.cpp
potato/librender/source/d3d12_backend/d3d12_root_signature.h
potato/librender/source/d3d12_backend/d3d12_sampler.cpp
potato/librender/source/d3d12_backend/d3d12_sampler.h
potato/librender/source/d3d12_backend/d3d12_swap_chain.cpp
potato/librender/source/d3d12_backend/d3d12_swap_chain.h
potato/librender/source/d3d12_backend/d3d12_texture.cpp
potato/librender/source/d3d12_backend/d3d12_texture.h
potato/librender/source/d3d12_backend/d3d12_utils.h

This import's Marcin's D3D12 backend, but without the accompanying changes in the rest of Potato.
It adds it as a flag behind `UP_BUILD_D3D12` (which can be set in `CMakeUserPresets.json` or by modifying the CMake cache directly, etc.)
It won't build as-is, as it will need to be updated for the many changes in main since the DX12 code was last fully merged.
The main purpose is to get the code in main so we can iterate on it together and not keep Marcin or DX12 banished to a separate branch that's nearly impossible to keep up-to-date.
My instinct is that we should continue refactoring the primary Potato rendering infrastructure until it's easier to fully finish/enable this backend without requiring extensive backend-specific changes or hacks throughout the rest of the codebase.

Import Marcin's D3D12 code

---

potato/librender/data/shaders/imgui.hlsl
potato/librender/include/potato/render/gpu_common.h
potato/librender/include/potato/render/gpu_device.h
potato/librender/include/potato/render/material.h
potato/librender/include/potato/render/renderer.h
potato/librender/include/potato/render/texture.h
potato/librender/source/d3d11_backend/d3d11_device.cpp
potato/librender/source/d3d11_backend/d3d11_device.h
potato/librender/source/d3d11_backend/d3d11_imgui_renderer.cpp
potato/librender/source/d3d11_backend/d3d11_platform.cpp
potato/librender/source/d3d11_backend/d3d11_platform.h
potato/librender/source/material.cpp
potato/librender/source/null_backend/null_objects.cpp
potato/librender/source/null_backend/null_objects.h
potato/librender/source/renderer.cpp
potato/librender/source/texture.cpp
resources/shaders/basic.hlsl
resources/shaders/full.hlsl

- Materials no longer create or bind a bunch of samplers
- Default samplers (linear and bilinear so far) are bound for all shaders
- Will probably need to be expanded eventually; simpler for now, will simplify D3D12 migration (I think)

Rework and expand samplers

---

potato/bin_shell/source/editors/asset_browser.cpp
potato/bin_shell/source/editors/asset_browser.h
potato/libeditor/include/potato/editor/imgui_ext.h
potato/libeditor/source/imgui_ext.cpp

- Only show direct children in main icon view
- Spacing tweaks and fixes
- Improved folder tree view and behavior
- Tweaks to back/forward/breadcrumb icons
- Added up folder button
- Condensed Add Asset / Add Folder buttons into a single dropdown

Asset Browser cleanups

---

potato/bin_shell/include/potato/shell/editor.h
potato/bin_shell/source/editor.cpp
potato/bin_shell/source/editors/asset_browser.cpp
potato/bin_shell/source/editors/asset_browser.h
potato/bin_shell/source/editors/game_editor.cpp
potato/bin_shell/source/editors/game_editor.h
potato/bin_shell/source/editors/log_window.h
potato/bin_shell/source/editors/material_editor.cpp
potato/bin_shell/source/editors/material_editor.h
potato/bin_shell/source/editors/scene_editor.cpp
potato/bin_shell/source/editors/scene_editor.h
potato/bin_shell/source/shell_app.cpp
potato/bin_shell/source/shell_app.h
potato/bin_shell/source/ui/editor_group.cpp

- Style tweaks to editor windows and panels
- Removed redundant SDL code (implemented in default backend)
- Fix: docking an editor window with another no longer causes overlay artefacts
- Fix: undocking windows is smooth and continuous
- Refactor panel layout configuration (implementation is gross)
- Disallow splitting top-level editor windows
- Fix: bug allowing content node of Asset Browser to become undocked
- Added a Panels/Reset Layout menu option for all editor windows
- Fix: activate new editor windows so menu bar is updated
- Windows can only be dragged from the titlebar
- Changed default panel layout for Scene Editor

Various imgui fixes and tweaks

---

potato/bin_shell/source/editors/log_window.cpp
potato/bin_shell/source/shell_app.cpp
potato/libeditor/source/editor_manager.cpp
potato/libeditor/source/imgui_ext.cpp
potato/libeditor/source/property_grid.cpp

- Slightly wider borders on windows
- Windows are transparent during docking
- Ensure Assets editor remains docked in the main window
- Remove some deprecated ImGui functions
Note: I tried upgrading to the latest imgui docking branch commit, which fixes a few bugs we're encountering... unfortunately it also _added_ a couple more serious bugs. Will wait for the next imgui release before we try that again.

Editor tweaks

---

potato/bin_shell/schema/scene.sap
potato/bin_shell/source/edit_components.h
potato/bin_shell/source/editors/material_editor.cpp
potato/bin_shell/source/editors/material_editor.h
potato/bin_shell/source/editors/scene_editor.cpp
potato/bin_shell/source/editors/scene_editor.h
potato/bin_shell/source/shell_app.cpp
potato/bin_shell/source/shell_app.h
potato/libeditor/include/potato/editor/imgui_ext.h
potato/libeditor/include/potato/editor/property_grid.h
potato/libeditor/source/imgui_ext.cpp
potato/libeditor/source/property_grid.cpp
potato/libreflex/include/potato/reflex/schema.h
potato/libreflex/source/serialize.cpp
potato/spud/CMakeLists.txt
potato/spud/include/potato/spud/ascii.h
potato/spud/include/potato/spud/memory_util.h
resources/scenes/test.scene

- Refactored Property Grid
- Custom Property Editors can be defined per primitive type (eventually: schema type customization)
- Property Grid is an app-level object, not per-document (for sharing custom editors)
- Layout refresh of Property Grid
- Prettified Property names
- General imgui style tweaks
- Schema refinements to better support Property Grid
- Various fixes

Property Grid updates

---

potato/bin_codegen/source/codegen_main.cpp
potato/bin_codegen/source/generators/schema_source_gen.cpp
potato/bin_shell/schema/scene.sap
potato/libaudio/schema/sound.sap
potato/libreflex/include/potato/reflex/schema.h
potato/libreflex/schema/common.sap
potato/librender/schema/material.sap
scripts/config/launch.vs.json.in

Closes #323 
The AssetRef templates were losing the attribute. Rather than fix that, I decided that having to declare every Asset type twice in IDL is silly and just flatted those declarations.

Fix the basics of Asset Browser... by fixing codegen

---

depends.cmake
external/imgui.cmake

We don't update all the way to 1.87 due to a bug with mouse input, the SDL backend, and the docking branch.

Update imgui to 1.87-WIP

---

external/dx12memalloc.cmake
external/imgui.cmake
external/libuv.cmake
external/nfd.cmake
external/soloud.cmake
external/sqlite.cmake
external/stb.cmake
external/tracy.cmake

Since VS upgrades introduce warnings that break third-party code.

Treat most external library headers paths as SYSTEM headers
