README.md

About section for people wandering into this

Update README.md for public

---

cmake/modules/up_target_natvis.cmake
external/CMakeLists.txt
external/glm.natvis
external/glm_natvis.cmake
source/library/foundation/support/CMakeLists.txt

Had to import a newer glm.natvis as the one in the latest release is outdated and doesn't work

Enable natvis support for glm

---

source/librender/CMakeLists.txt
source/librender/private/d3d11_backend/d3d11_buffer.h
source/librender/private/d3d11_backend/d3d11_command_list.h
source/librender/private/d3d11_backend/d3d11_device.h
source/librender/private/d3d11_backend/d3d11_factory.h
source/librender/private/d3d11_backend/d3d11_pipeline_state.h
source/librender/private/d3d11_backend/d3d11_platform.h
source/librender/private/d3d11_backend/d3d11_resource_view.h
source/librender/private/d3d11_backend/d3d11_sampler.h
source/librender/private/d3d11_backend/d3d11_swap_chain.h
source/librender/private/d3d11_backend/d3d11_texture.h

Got lost refactor and test don't enforce any backend.
Need to figure out the best way to handle that.

Fix D3D build

---

external/config.cmake

Much faster for repeated CMake generate commands.

Fetch zip archives instead of git repos

---

source/bin_shell/private/CMakeLists.txt
source/bin_shell/private/game_panel.cpp
source/bin_shell/private/hierarchy_panel.cpp
source/bin_shell/private/inspector_panel.cpp
source/bin_shell/private/scene_panel.cpp
source/bin_shell/private/shell_app.cpp
source/bin_shell/private/shell_app.h
source/bin_shell/public/potato/shell/CMakeLists.txt
source/bin_shell/public/potato/shell/panel.h
source/bin_shell/public/potato/shell/selection.h

Super hacky and rough initial entity inspector, and hierarchy view.
- ImGui docking branch
- Rearchitected shell views/documents
- Hierachy panel
- Inspector panel
- UX improvements to scene/game view

Initial Inspector UX 

---

external/sdl2_vc.cmake

This has, uh, been broken for a while

Fix SDL2 auto-download

---

scripts/build/compile_schema.py
scripts/build/type_info.py
source/bin_shell/private/editors/game_editor.cpp
source/bin_shell/private/editors/scene_editor.cpp
source/bin_shell/private/shell_app.cpp
source/bin_shell/private/ui/menu.cpp
source/bin_shell/schema/components.sap
source/libeditor/private/imgui_ext.cpp
source/libeditor/private/property_grid.cpp
source/libeditor/public/potato/editor/imgui_ext.h
source/libeditor/public/potato/editor/property_grid.h
source/libformat/public/potato/format/format.h
source/libreflex/CMakeLists.txt
source/libreflex/public/potato/reflex/schema.h
source/libreflex/public/potato/reflex/type.h
source/libreflex/schema/constraint.sap
source/libreflex/schema/tools.sap
source/spud/public/potato/spud/vector.h

- Editor attributes
- Vector editor is better

Property grid refinements

---

external/CMakeLists.txt
external/dmon.cmake
external/dmon/.clang-format
external/dmon/.gitignore
external/dmon/LICENSE
external/dmon/README.md
external/dmon/dmon.h
external/dmon/test.c
source/bin_recon/CMakeLists.txt
source/bin_recon/private/recon_app.cpp
source/bin_recon/private/recon_protocol.cpp
source/bin_recon/public/potato/recon/recon_app.h
source/bin_recon/public/potato/recon/recon_protocol.h
source/bin_shell/CMakeLists.txt
source/bin_shell/private/recon_client.cpp
source/bin_shell/private/recon_client.h
source/bin_shell/private/shell_app.cpp
source/bin_shell/private/shell_app.h
source/libruntime/CMakeLists.txt
source/libruntime/private/filesystem.cpp
source/libruntime/public/potato/runtime/concurrent_queue.h
source/libruntime/public/potato/runtime/filesystem.h
source/libtools/public/potato/tools/project.h

- recon `-server` flag where it monitors the resource directory and imports on change
- shell automatically starts recon in server mode
- recon logs piped to shell

recon server mode

---

.github/workflows/main.yml
documentation/README.md
documentation/getting-started.md
documentation/tracy.md
external/CMakeLists.txt
external/config.cmake
external/tracy.cmake
source/bin_shell/private/shell_app.cpp
source/libruntime/CMakeLists.txt

https://github.com/wolfpld/tracy

Basic integration of Tracy profiler

---

resources/scenes/test.scene
source/bin_shell/private/editors/scene_editor.cpp

Pretty-print when saving so merging will be _less_ awful

Actually load scene from disk again

---

source/.clang-tidy

GitHub's auto-merge will bypass CI checks, which is how the last two commits got through to main. :/

Fix build round two

---

.github/workflows/build-ubuntu.yml
.github/workflows/check-clang.yml
source/bin_recon/private/file_hash_cache.cpp
source/bin_recon/private/file_hash_cache.h
source/spud/CMakeLists.txt
source/spud/public/potato/spud/_hash_table.h
source/spud/public/potato/spud/hash.h
source/spud/public/potato/spud/hash_map.h
source/spud/public/potato/spud/hash_set.h
source/spud/tests/test_hash_map.cpp
source/spud/tests/test_hash_set.cpp

Somewhat simplified (see notes in hash_map.h) but mostly the same algorithm.

SwissTable-based hash_map and hash_set

---

depends.cmake
potato/bin_shell/source/edit_components.cpp
potato/libgame/CMakeLists.txt
potato/libgame/include/potato/game/components/rigidbody_component.h
potato/libgame/source/systems/physics_system.cpp

Use Bullet3 for physics simulation

---

potato/bin_recon/source/importer_factory.cpp
potato/bin_recon/source/posql.cpp
potato/bin_recon/source/posql.h
potato/bin_shell/source/editor.cpp
potato/bin_shell/source/editors/asset_browser.cpp
potato/libeditor/source/imgui_backend.cpp
potato/libeditor/source/imgui_ext.cpp
potato/libeditor/source/property_grid.cpp
potato/libgame/include/potato/game/entity_manager.h
potato/libgame/source/space.cpp
potato/librecon/source/recon_client.cpp
potato/libruntime/include/potato/runtime/assertion.h
potato/libruntime/source/asset_loader.cpp
potato/libruntime/source/filesystem.cpp
potato/libruntime/source/io_loop.cpp
potato/libruntime/source/path.cpp

Guards provide guaranteed early-return behavior (in builds with debug features enabled).

Guards vs asserts

---

potato/librender/source/d3d11_backend/d3d11_swap_chain.cpp

Was off, which caused mad uncapped framerates, and made GPUs sad

Force VSync on

---

potato/spud/include/potato/spud/static_id.h

adding explicit compare operators to make sure staticid is using hashed value over binary compare.

fixing staticid compare

---

potato/bin_shell/schema/scene.sap
potato/bin_shell/source/edit_components.cpp
potato/bin_shell/source/scene_doc.cpp
potato/libeditor/source/property_grid.cpp
potato/libreflex/include/potato/reflex/schema.h
potato/libreflex/schema/common.sap
potato/libreflex/source/serialize.cpp
resources/scenes/test.scene

- Nuke `quat` type from schema

Use Euler angles for Transform rotation in editor

---

potato/bin_shell/source/shell_app.cpp
potato/bin_shell/source/shell_app.h

Add ability to show the imgui demo window

---

depends.cmake

See https://github.blog/2021-09-01-improving-git-protocol-security-github/

Update git repository URLs

---

CMakeLists.txt
CMakePresets.json

- Update presets version
- Force disable C++20 modules

CMake tweaks

---

.github/workflows/build-ubuntu.yml
.github/workflows/build-windows.yml
.github/workflows/check-clang.yml

Update actions/cache github action
